import { Form, Head, router, usePage } from '@inertiajs/react';
import AdminLayout from '@/Components/AdminLayout';
import { useMemo, useState } from 'react';
import {
    Activity, CreditCard, MoreHorizontal, Plus, Search, Users,
    UserRoundCheck, WalletCards, X, Zap, Bell, Pencil, Trash2
} from 'lucide-react';

type Member = { id: number; name: string; email: string; phone: string | null; membershipPlanId: number | null; membershipStartsAt: string | null; membershipEndsAt: string | null; initials: string; plan: string; status: string; joined: string; visits: number; accent: string };
type Metrics = { activeMembers: number; todayCheckIns: number; currentlyInside: number; monthlyRevenue: number; atRiskMembers: number };
type DropdownOptions = Record<string, string[]>;
type MembershipPlan = { id:number;name:string;price:string;billingCycle:string;durationDays:number;isActive:boolean;activeSubscriptionsCount:number };
type PaymentMember = { id:number;name:string;plan:string|null };
type PaymentRecord = { id:number;memberId:number;memberName:string;plan:string|null;amount:string;status:string;paymentMethod:string;reference:string|null;paidAt:string|null };
type AttendanceMember = { id:number;name:string };
type AttendanceRecord = { id:number;memberId:number;memberName:string;checkedInAt:string;checkedOutAt:string|null;notes:string|null };
type Trainer = { id:number;name:string;email:string;phone:string|null;specialty:string;isActive:boolean;upcomingSessionsCount:number };
type Booking = { id:number;memberId:number;memberName:string };
type GymSession = { id:number;trainerId:number|null;trainerName:string|null;name:string;sessionType:string;startsAt:string;endsAt:string;capacity:number;isCancelled:boolean;bookings:Booking[] };
type Lead = { id:number;name:string;email:string|null;phone:string|null;interest:string;source:string|null;status:string;nextFollowUpAt:string|null;notes:string|null;convertedUserId:number|null };
type Props = { members: Member[]; metrics: Metrics; dropdownOptions: DropdownOptions; membershipPlans: MembershipPlan[]; paymentMembers:PaymentMember[];payments:PaymentRecord[];attendances:AttendanceRecord[];trainers:Trainer[];bookingMembers:AttendanceMember[];gymSessions:GymSession[];leads:Lead[];activeSection: string };

function Avatar({ initials, color = 'violet' }: { initials: string; color?: string }) {
    return <span className={`avatar avatar-${color}`}>{initials}</span>;
}

function Dashboard({ members, metrics, dropdownOptions, membershipPlans, paymentMembers, payments, attendances, trainers, bookingMembers, gymSessions, leads, activeSection }: Props) {
    const page = usePage<{ auth: { user: { name: string } }; gym: { name: string } | null }>();
    const currentUser = page.props.auth.user;
    const gymName = page.props.gym?.name ?? 'Gym workspace';
    const [query, setQuery] = useState('');
    const [modal, setModal] = useState(false);
    const [editingMember, setEditingMember] = useState<Member | null>(null);
    const [editingPayment, setEditingPayment] = useState<PaymentRecord | null>(null);
    const [paymentModal, setPaymentModal] = useState(false);
    const [editingTrainer, setEditingTrainer] = useState<Trainer | null>(null);
    const [trainerModal, setTrainerModal] = useState(false);
    const [editingSession, setEditingSession] = useState<GymSession | null>(null);
    const [sessionModal, setSessionModal] = useState(false);
    const [bookingSession, setBookingSession] = useState<GymSession | null>(null);
    const [editingLead, setEditingLead] = useState<Lead | null>(null);
    const [leadModal, setLeadModal] = useState(false);
    const [convertingLead, setConvertingLead] = useState<Lead | null>(null);
    const [toast, setToast] = useState('');

    const filtered = useMemo(() => members.filter(m => `${m.name} ${m.plan} ${m.status}`.toLowerCase().includes(query.toLowerCase())), [members, query]);
    const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2600); };

    return <>
        <Head title={`${activeSection} · ${gymName}`} />
        <AdminLayout activeSection={activeSection} user={currentUser}>
                    {activeSection === 'Overview' ? <Overview metrics={metrics} managerName={currentUser.name} gymName={gymName} openModal={() => setModal(true)} payments={payments} attendances={attendances}/> :
                        activeSection === 'Members' ? <Members members={filtered} query={query} setQuery={setQuery} openModal={() => setModal(true)} edit={setEditingMember} remove={member => window.confirm(`Delete ${member.name}? This cannot be undone.`) && router.delete(`/admin/members/${member.id}`, { preserveScroll: true })}/> :
                        activeSection === 'Payments' ? <Payments payments={payments} create={()=>setPaymentModal(true)} edit={setEditingPayment}/> :
                        activeSection === 'Trainers' ? <Trainers trainers={trainers} create={()=>setTrainerModal(true)} edit={setEditingTrainer}/> :
                        activeSection === 'Schedule' ? <Schedule sessions={gymSessions} create={()=>setSessionModal(true)} edit={setEditingSession} book={setBookingSession}/> :
                        activeSection === 'Leads' ? <Leads leads={leads} create={()=>setLeadModal(true)} edit={setEditingLead} convert={setConvertingLead}/> : null}
        </AdminLayout>
        {modal && <AddMember plans={membershipPlans.filter(plan=>plan.isActive)} close={() => setModal(false)} saved={() => notify('Member added successfully')}/>}
        {editingMember && <EditMember member={editingMember} plans={membershipPlans.filter(plan=>plan.isActive || plan.id===editingMember.membershipPlanId)} close={() => setEditingMember(null)}/>}
        {(paymentModal || editingPayment) && <PaymentModal payment={editingPayment} members={paymentMembers} methods={dropdownOptions.payment_methods ?? []} close={()=>{setPaymentModal(false);setEditingPayment(null);}}/>}
        {(trainerModal || editingTrainer) && <TrainerModal trainer={editingTrainer} specialties={dropdownOptions.trainer_specialties??[]} close={()=>{setTrainerModal(false);setEditingTrainer(null);}}/>}
        {(sessionModal || editingSession) && <SessionModal session={editingSession} trainers={trainers.filter(trainer=>trainer.isActive||trainer.id===editingSession?.trainerId)} sessionTypes={dropdownOptions.session_types??[]} close={()=>{setSessionModal(false);setEditingSession(null);}}/>}
        {bookingSession && <BookingModal session={bookingSession} members={bookingMembers} close={()=>setBookingSession(null)}/>}
        {(leadModal || editingLead) && <LeadModal lead={editingLead} interests={dropdownOptions.lead_interests??[]} close={()=>{setLeadModal(false);setEditingLead(null);}}/>}
        {convertingLead && <ConvertLeadModal lead={convertingLead} plans={membershipPlans.filter(plan=>plan.isActive)} close={()=>setConvertingLead(null)}/>}
        {toast && <div className="toast"><span>✓</span>{toast}</div>}
    </>;
}

function Overview({ metrics, managerName, gymName, openModal, payments, attendances }: { metrics: Metrics; managerName: string; gymName: string; openModal: () => void; payments:PaymentRecord[];attendances:AttendanceRecord[] }) {
    const firstName = managerName.split(' ')[0];
    const today = new Intl.DateTimeFormat('en-IN', { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date()).toUpperCase();
    const revenue = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(metrics.monthlyRevenue);
    const exportReport = () => { const rows=[['Metric','Value'],['Active members',metrics.activeMembers],['Today check-ins',metrics.todayCheckIns],['Currently inside',metrics.currentlyInside],['Monthly revenue',metrics.monthlyRevenue],['At-risk members',metrics.atRiskMembers]];const blob=new Blob([rows.map(row=>row.join(',')).join('\n')],{type:'text/csv'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${gymName.toLowerCase().replace(/[^a-z0-9]+/g,'-')}-report.csv`;link.click();URL.revokeObjectURL(link.href);};
    const activities=[...attendances.slice(0,3).map(item=>({id:`attendance-${item.id}`,title:`${item.memberName} checked in`,time:item.checkedInAt})),...payments.slice(0,3).map(item=>({id:`payment-${item.id}`,title:`${item.memberName} payment · ₹${Number(item.amount).toLocaleString('en-IN')}`,time:item.paidAt}))].filter(item=>item.time).sort((a,b)=>new Date(b.time!).getTime()-new Date(a.time!).getTime()).slice(0,4);
    return <>
        <section className="page-heading"><div><span className="eyebrow">{today}</span><h1>Good morning, {firstName} <span>👋</span></h1><p>Here’s what’s happening at {gymName} today.</p></div><div className="heading-actions"><button className="secondary" onClick={exportReport}>Export report</button><button className="primary" onClick={openModal}><Plus size={18}/> Add member</button></div></section>
        <section className="stats-grid">
            <Stat icon={<Users/>} label="Active members" value={metrics.activeMembers.toLocaleString('en-IN')} detail="Current active plans" color="violet"/>
            <Stat icon={<UserRoundCheck/>} label="Today's check-ins" value={metrics.todayCheckIns.toLocaleString('en-IN')} detail={`${metrics.currentlyInside} currently inside`} color="green"/>
            <Stat icon={<WalletCards/>} label="Monthly revenue" value={revenue} detail="No payments recorded yet" color="blue"/>
            <Stat icon={<Activity/>} label="At-risk members" value={metrics.atRiskMembers.toLocaleString('en-IN')} detail="Expiring within 7 days" color="orange"/>
        </section>
        <section className="dashboard-grid">
            <div className="card revenue-card"><div className="card-head"><div><h2>Revenue overview</h2><p>Membership revenue this month</p></div></div><div className="revenue-meta"><strong>{revenue}</strong><small>{payments.filter(payment=>payment.status==='paid').length} recent paid transactions</small></div>{payments.length===0?<div className="chart-empty"><WalletCards/><strong>No revenue data yet</strong><span>Recorded membership payments will appear here.</span></div>:<div className="overview-payments">{payments.slice(0,5).map(payment=><div key={payment.id}><span>{payment.memberName}</span><strong>₹{Number(payment.amount).toLocaleString('en-IN')}</strong><i className={`status status-${payment.status}`}>{payment.status}</i></div>)}</div>}</div>
            <div className="card attendance-card"><div className="card-head"><div><h2>Club traffic</h2><p>Live attendance status</p></div><span className="live"><i/> Live</span></div><div className="occupancy"><div><span>Currently inside</span><strong>{metrics.currentlyInside}</strong><small>members</small></div><div className="ring" style={{'--p':metrics.currentlyInside?'100%':'0%'} as React.CSSProperties}><span>{metrics.currentlyInside}</span></div></div><div className="capacity-bar"><i style={{width:metrics.currentlyInside?'100%':'0%'}}/><span/></div><div className="peak neutral"><Zap size={16}/><p><strong>{metrics.todayCheckIns} check-ins today</strong><span>{metrics.currentlyInside?'Live visits are currently in progress.':'No members are currently checked in.'}</span></p></div></div>
            <div className="card activity-card"><div className="card-head"><div><h2>Live activity</h2><p>Latest check-ins and payments</p></div></div>{activities.length===0?<div className="compact-empty"><Activity/><strong>No activity yet</strong><span>Member check-ins and payments will appear here.</span></div>:<div className="activity-list">{activities.map(item=><div className="activity-item" key={item.id}><span className="avatar avatar-violet"><Activity/></span><div><strong>{item.title}</strong><span>{new Date(item.time!).toLocaleString('en-IN')}</span></div></div>)}</div>}</div>
            <div className="card renewals-card"><div className="card-head"><div><h2>Membership alerts</h2><p>Renewals needing attention</p></div></div><div className="renewal-count"><strong>{metrics.atRiskMembers}</strong><span>members expire in the next 7 days</span></div>{metrics.atRiskMembers === 0 && <div className="compact-empty small"><Bell/><strong>No renewal alerts</strong><span>Upcoming expirations will appear here.</span></div>}</div>
        </section>
    </>;
}

function Stat({ icon,label,value,detail,color }: any) { return <div className="stat-card"><div className={`stat-icon ${color}`}>{icon}</div><div className="stat-title">{label}<MoreHorizontal size={18}/></div><strong>{value}</strong><div className="trend"><span>{detail}</span></div></div>; }

function Members({members,query,setQuery,openModal,edit,remove}:{members:Member[];query:string;setQuery:(s:string)=>void;openModal:()=>void;edit:(member:Member)=>void;remove:(member:Member)=>void}) { return <>
    <section className="page-heading"><div><span className="eyebrow">PEOPLE</span><h1>Members</h1><p>Manage profiles, plans and member engagement.</p></div><button className="primary" onClick={openModal}><Plus size={18}/> Add member</button></section>
    <div className="card members-card"><div className="member-toolbar"><div className="table-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search members..."/></div><div className="member-summary"><b>{members.length}</b> total members</div></div>{members.length === 0 ? <div className="compact-empty table-empty"><Users/><strong>No members yet</strong><span>Add your first member to populate this workspace.</span><button className="secondary empty-state-action" onClick={openModal}>Add first member</button></div> : <div className="member-table"><div className="member-row labels"><span>Member</span><span>Membership</span><span>Status</span><span>Visits</span><span>Joined</span><span>Actions</span></div>{members.map(m=><div className="member-row member-row-link" key={m.id} role="link" tabIndex={0} onClick={()=>router.visit(`/admin/members/${m.id}`)} onKeyDown={event=>{if(event.currentTarget===event.target&&(event.key==='Enter'||event.key===' ')){event.preventDefault();router.visit(`/admin/members/${m.id}`);}}}><div className="member-name"><Avatar initials={m.initials} color={m.accent}/><strong>{m.name}</strong></div><span>{m.plan}</span><span><i className={`status status-${m.status.toLowerCase()}`}>{m.status}</i></span><span><b>{m.visits}</b> this month</span><span>{m.joined}</span><div className="row-actions"><button className="edit-action" onClick={event=>{event.stopPropagation();edit(m);}} aria-label={`Edit ${m.name}`} title="Edit member"><Pencil/></button><button className="delete-action" onClick={event=>{event.stopPropagation();remove(m);}} aria-label={`Delete ${m.name}`} title="Delete member"><Trash2/></button></div></div>)}</div>}</div>
    </>; }

function AddMember({plans,close,saved}:{plans:MembershipPlan[];close:()=>void;saved:()=>void}) { return <div className="modal-backdrop" onMouseDown={close}><Form action="/admin/members" method="post" className="modal" onMouseDown={event=>event.stopPropagation()} onSuccess={()=>{close();saved();}} resetOnSuccess>{({errors,processing})=><><div className="modal-head"><div><h2>Add a new member</h2><p>Create their profile, login credentials and membership.</p></div><button type="button" onClick={close}><X/></button></div><label>Full name<input name="name" autoFocus placeholder="e.g. Aarav Sharma" required/>{errors.name&&<em>{errors.name}</em>}</label><div className="form-row"><label>Email<input name="email" type="email" placeholder="aarav@example.com" required/>{errors.email&&<em>{errors.email}</em>}</label><label>Phone<input name="phone" placeholder="+91 98765 43210"/>{errors.phone&&<em>{errors.phone}</em>}</label></div><div className="form-row"><label>Temporary password<input name="password" type="password" autoComplete="new-password" minLength={8} required/>{errors.password&&<em>{errors.password}</em>}</label><label>Confirm password<input name="password_confirmation" type="password" autoComplete="new-password" minLength={8} required/></label></div><div className="form-row"><label>Membership plan<select name="membership_plan_id" defaultValue=""><option value="">No active plan</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name} · ₹{Number(plan.price).toLocaleString('en-IN')}</option>)}</select>{errors.membership_plan_id&&<em>{errors.membership_plan_id}</em>}</label><label>Starts on<input name="membership_starts_at" type="date"/>{errors.membership_starts_at&&<em>{errors.membership_starts_at}</em>}</label></div><label>Custom end date <small>Leave blank to use the plan duration.</small><input name="membership_ends_at" type="date"/>{errors.membership_ends_at&&<em>{errors.membership_ends_at}</em>}</label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={processing}>{processing?'Creating…':'Create member'}</button></div></>}</Form></div>; }

function EditMember({member,plans,close}:{member:Member;plans:MembershipPlan[];close:()=>void}) {
    const [form,setForm] = useState({name:member.name,email:member.email,phone:member.phone ?? '',membership_plan_id:member.membershipPlanId?.toString() ?? '',membership_starts_at:member.membershipStartsAt ?? '',membership_ends_at:member.membershipEndsAt ?? ''});
    const update = (field:keyof typeof form,value:string) => setForm(current=>({...current,[field]:value}));
    const submit = (event:React.FormEvent) => {event.preventDefault();router.put(`/admin/members/${member.id}`,form,{preserveScroll:true,onSuccess:close});};
    return <div className="modal-backdrop" onMouseDown={close}><form className="modal" onMouseDown={event=>event.stopPropagation()} onSubmit={submit}><div className="modal-head"><div><h2>Edit member</h2><p>Update profile and membership information.</p></div><button type="button" onClick={close}><X/></button></div><label>Full name<input autoFocus value={form.name} onChange={event=>update('name',event.target.value)} required/></label><div className="form-row"><label>Email<input type="email" value={form.email} onChange={event=>update('email',event.target.value)} required/></label><label>Phone<input value={form.phone} onChange={event=>update('phone',event.target.value)}/></label></div><div className="form-row"><label>Membership plan<select value={form.membership_plan_id} onChange={event=>update('membership_plan_id',event.target.value)}><option value="">No active plan</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label>Starts on<input type="date" value={form.membership_starts_at} onChange={event=>update('membership_starts_at',event.target.value)}/></label></div><label>Ends on<input type="date" value={form.membership_ends_at} onChange={event=>update('membership_ends_at',event.target.value)}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit"><Pencil/> Save changes</button></div></form></div>;
}


function Trainers({trainers,create,edit}:{trainers:Trainer[];create:()=>void;edit:(trainer:Trainer)=>void}) { return <><section className="page-heading"><div><span className="eyebrow">COACHING TEAM</span><h1>Trainers</h1><p>Manage coaches and connect them to scheduled sessions.</p></div><button className="primary" onClick={create}><Plus size={18}/> Add trainer</button></section>{trainers.length===0?<div className="card compact-empty table-empty"><Users/><strong>No trainers yet</strong><span>Add your first trainer before scheduling coached sessions.</span><button className="secondary empty-state-action" onClick={create}>Add first trainer</button></div>:<section className="membership-plan-grid">{trainers.map(trainer=><article className="card membership-plan-card" key={trainer.id}><div className="card-head"><div><h2>{trainer.name}</h2><p>{trainer.specialty}</p></div><i className={`status status-${trainer.isActive?'active':'inactive'}`}>{trainer.isActive?'Active':'Inactive'}</i></div><span>{trainer.email}</span><span>{trainer.phone??'No phone'} · {trainer.upcomingSessionsCount} upcoming sessions</span><div className="membership-plan-actions"><button className="secondary" onClick={()=>edit(trainer)}><Pencil/> Edit</button><button className="danger-icon" onClick={()=>window.confirm(`Delete ${trainer.name}? Existing sessions will remain unassigned.`)&&router.delete(`/admin/trainers/${trainer.id}`)}><Trash2/></button></div></article>)}</section>}</>; }

function TrainerModal({trainer,specialties,close}:{trainer:Trainer|null;specialties:string[];close:()=>void}) { return <div className="modal-backdrop" onMouseDown={close}><Form action={trainer?`/admin/trainers/${trainer.id}`:'/admin/trainers'} method={trainer?'put':'post'} className="modal" onMouseDown={event=>event.stopPropagation()} onSuccess={close}>{({errors,processing})=><><div className="modal-head"><div><h2>{trainer?'Edit trainer':'Add trainer'}</h2><p>Create the coach profile used by the schedule.</p></div><button type="button" onClick={close}><X/></button></div><label>Name<input name="name" defaultValue={trainer?.name??''} required/>{errors.name&&<em>{errors.name}</em>}</label><div className="form-row"><label>Email<input name="email" type="email" defaultValue={trainer?.email??''} required/>{errors.email&&<em>{errors.email}</em>}</label><label>Phone<input name="phone" defaultValue={trainer?.phone??''}/>{errors.phone&&<em>{errors.phone}</em>}</label></div><label>Specialty<select name="specialty" defaultValue={trainer?.specialty??specialties[0]??'General fitness'}>{(specialties.length?specialties:['General fitness']).map(value=><option key={value}>{value}</option>)}</select>{errors.specialty&&<em>{errors.specialty}</em>}</label><label className="status-toggle"><input type="hidden" name="is_active" value="0"/><input name="is_active" type="checkbox" value="1" defaultChecked={trainer?.isActive??true}/> Active trainer</label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={processing}>{processing?'Saving…':'Save trainer'}</button></div></>}</Form></div>; }

function Schedule({sessions,create,edit,book}:{sessions:GymSession[];create:()=>void;edit:(session:GymSession)=>void;book:(session:GymSession)=>void}) { return <><section className="page-heading"><div><span className="eyebrow">PROGRAM CALENDAR</span><h1>Schedule</h1><p>Schedule sessions, control capacity, and manage member bookings.</p></div><button className="primary" onClick={create}><Plus size={18}/> Schedule session</button></section><div className="card members-card">{sessions.length===0?<div className="compact-empty table-empty"><Activity/><strong>No sessions scheduled</strong><span>Create the first class or personal training session.</span><button className="secondary empty-state-action" onClick={create}>Schedule first session</button></div>:<div className="session-list">{sessions.map(session=><article className={`session-row ${session.isCancelled?'cancelled':''}`} key={session.id}><div><strong>{session.name}</strong><span>{session.sessionType} · {session.trainerName??'Unassigned trainer'}</span></div><div><strong>{new Date(session.startsAt).toLocaleString('en-IN')}</strong><span>to {new Date(session.endsAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</span></div><div><strong>{session.bookings.length} / {session.capacity}</strong><span>{session.isCancelled?'Cancelled':'booked'}</span></div><div className="session-members"><span>{session.bookings.map(item=><button key={item.id} title="Cancel booking" onClick={()=>window.confirm(`Cancel ${item.memberName}'s booking?`)&&router.delete(`/admin/bookings/${item.id}`,{preserveScroll:true})}>{item.memberName} ×</button>)}</span></div><div className="row-actions">{!session.isCancelled&&session.bookings.length<session.capacity&&<button className="checkout-action" onClick={()=>book(session)} title="Book member"><Plus/></button>}<button className="edit-action" onClick={()=>edit(session)}><Pencil/></button><button className="delete-action" onClick={()=>window.confirm(`Delete ${session.name}?`)&&router.delete(`/admin/gym-sessions/${session.id}`)}><Trash2/></button></div></article>)}</div>}</div></>; }

function SessionModal({session,trainers,sessionTypes,close}:{session:GymSession|null;trainers:Trainer[];sessionTypes:string[];close:()=>void}) { const now=new Date();const start=new Date(now.getTime()-now.getTimezoneOffset()*60000+3600000).toISOString().slice(0,16);const end=new Date(now.getTime()-now.getTimezoneOffset()*60000+7200000).toISOString().slice(0,16);return <div className="modal-backdrop" onMouseDown={close}><Form action={session?`/admin/gym-sessions/${session.id}`:'/admin/gym-sessions'} method={session?'put':'post'} className="modal" onMouseDown={event=>event.stopPropagation()} onSuccess={close}>{({errors,processing})=><><div className="modal-head"><div><h2>{session?'Edit session':'Schedule session'}</h2><p>Define timing, trainer, and booking capacity.</p></div><button type="button" onClick={close}><X/></button></div><label>Session name<input name="name" defaultValue={session?.name??''} required/>{errors.name&&<em>{errors.name}</em>}</label><div className="form-row"><label>Session type<select name="session_type" defaultValue={session?.sessionType??sessionTypes[0]??'Group class'}>{(sessionTypes.length?sessionTypes:['Group class']).map(value=><option key={value}>{value}</option>)}</select></label><label>Trainer<select name="trainer_id" defaultValue={session?.trainerId??''}><option value="">Unassigned</option>{trainers.map(trainer=><option key={trainer.id} value={trainer.id}>{trainer.name}</option>)}</select>{errors.trainer_id&&<em>{errors.trainer_id}</em>}</label></div><div className="form-row"><label>Starts at<input name="starts_at" type="datetime-local" defaultValue={session?.startsAt??start} required/>{errors.starts_at&&<em>{errors.starts_at}</em>}</label><label>Ends at<input name="ends_at" type="datetime-local" defaultValue={session?.endsAt??end} required/>{errors.ends_at&&<em>{errors.ends_at}</em>}</label></div><label>Capacity<input name="capacity" type="number" min="1" max="1000" defaultValue={session?.capacity??20} required/>{errors.capacity&&<em>{errors.capacity}</em>}</label><label className="status-toggle"><input type="hidden" name="is_cancelled" value="0"/><input name="is_cancelled" type="checkbox" value="1" defaultChecked={session?.isCancelled??false}/> Cancel this session</label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={processing}>{processing?'Saving…':'Save session'}</button></div></>}</Form></div>; }

function BookingModal({session,members,close}:{session:GymSession;members:AttendanceMember[];close:()=>void}) { const bookedIds=new Set(session.bookings.map(item=>item.memberId));const available=members.filter(member=>!bookedIds.has(member.id));return <div className="modal-backdrop" onMouseDown={close}><Form action="/admin/bookings" method="post" className="modal" onMouseDown={event=>event.stopPropagation()} onSuccess={close}>{({errors,processing})=><><div className="modal-head"><div><h2>Book a member</h2><p>{session.name} has {session.capacity-session.bookings.length} places remaining.</p></div><button type="button" onClick={close}><X/></button></div><input type="hidden" name="gym_session_id" value={session.id}/><label>Member<select name="user_id" defaultValue="" required><option value="" disabled>Select a member</option>{available.map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select>{errors.user_id&&<em>{errors.user_id}</em>}{errors.booking&&<em>{errors.booking}</em>}</label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={processing||available.length===0}>{processing?'Booking…':'Book member'}</button></div></>}</Form></div>; }

function Leads({leads,create,edit,convert}:{leads:Lead[];create:()=>void;edit:(lead:Lead)=>void;convert:(lead:Lead)=>void}) { return <><section className="page-heading"><div><span className="eyebrow">SALES PIPELINE</span><h1>Leads</h1><p>Track prospects, follow-ups, and conversions into members.</p></div><button className="primary" onClick={create}><Plus size={18}/> Add lead</button></section><div className="lead-stats"><article><strong>{leads.filter(lead=>lead.status==='new').length}</strong><span>New</span></article><article><strong>{leads.filter(lead=>lead.status==='contacted').length}</strong><span>Contacted</span></article><article><strong>{leads.filter(lead=>lead.status==='qualified').length}</strong><span>Qualified</span></article><article><strong>{leads.filter(lead=>lead.status==='converted').length}</strong><span>Converted</span></article></div><div className="card members-card">{leads.length===0?<div className="compact-empty table-empty"><Users/><strong>No leads captured</strong><span>Add your first prospect to start the sales pipeline.</span><button className="secondary empty-state-action" onClick={create}>Add first lead</button></div>:<div className="lead-table"><div className="lead-row labels"><span>Prospect</span><span>Interest</span><span>Status</span><span>Follow-up</span><span>Source</span><span>Actions</span></div>{leads.map(lead=><div className="lead-row" key={lead.id}><div><strong>{lead.name}</strong><span>{lead.email??lead.phone}</span></div><span>{lead.interest}</span><i className={`status status-${lead.status}`}>{lead.status}</i><span>{lead.nextFollowUpAt?new Date(lead.nextFollowUpAt).toLocaleString('en-IN'):'—'}</span><span>{lead.source??'—'}</span><div className="row-actions">{lead.status!=='converted'&&<><button className="checkout-action" onClick={()=>convert(lead)} title="Convert to member"><UserRoundCheck/></button><button className="edit-action" onClick={()=>edit(lead)}><Pencil/></button><button className="delete-action" onClick={()=>window.confirm(`Delete ${lead.name}?`)&&router.delete(`/admin/leads/${lead.id}`)}><Trash2/></button></>}</div></div>)}</div>}</div></>; }

function LeadModal({lead,interests,close}:{lead:Lead|null;interests:string[];close:()=>void}) { return <div className="modal-backdrop" onMouseDown={close}><Form action={lead?`/admin/leads/${lead.id}`:'/admin/leads'} method={lead?'put':'post'} className="modal" onMouseDown={event=>event.stopPropagation()} onSuccess={close}>{({errors,processing})=><><div className="modal-head"><div><h2>{lead?'Update lead':'Add lead'}</h2><p>Capture contact details and plan the next follow-up.</p></div><button type="button" onClick={close}><X/></button></div><label>Name<input name="name" defaultValue={lead?.name??''} required/>{errors.name&&<em>{errors.name}</em>}</label><div className="form-row"><label>Email<input name="email" type="email" defaultValue={lead?.email??''}/>{errors.email&&<em>{errors.email}</em>}</label><label>Phone<input name="phone" defaultValue={lead?.phone??''}/>{errors.phone&&<em>{errors.phone}</em>}</label></div><div className="form-row"><label>Interest<select name="interest" defaultValue={lead?.interest??interests[0]??'Gym membership'}>{(interests.length?interests:['Gym membership']).map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select name="status" defaultValue={lead?.status??'new'}><option value="new">New</option><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="lost">Lost</option></select></label></div><div className="form-row"><label>Source<input name="source" defaultValue={lead?.source??''} placeholder="Website, referral, walk-in…"/></label><label>Next follow-up<input name="next_follow_up_at" type="datetime-local" defaultValue={lead?.nextFollowUpAt??''}/></label></div><label>Notes<textarea name="notes" defaultValue={lead?.notes??''} rows={3}/>{errors.notes&&<em>{errors.notes}</em>}</label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={processing}>{processing?'Saving…':'Save lead'}</button></div></>}</Form></div>; }

function ConvertLeadModal({lead,plans,close}:{lead:Lead;plans:MembershipPlan[];close:()=>void}) { return <div className="modal-backdrop" onMouseDown={close}><Form action={`/admin/leads/${lead.id}/convert`} method="post" className="modal" onMouseDown={event=>event.stopPropagation()} onSuccess={close}>{({errors,processing})=><><div className="modal-head"><div><h2>Convert {lead.name}</h2><p>Create a member login and optionally activate a membership.</p></div><button type="button" onClick={close}><X/></button></div><label>Member email<input name="email" type="email" defaultValue={lead.email??''} required/>{errors.email&&<em>{errors.email}</em>}</label><div className="form-row"><label>Temporary password<input name="password" type="password" minLength={8} required/>{errors.password&&<em>{errors.password}</em>}</label><label>Confirm password<input name="password_confirmation" type="password" minLength={8} required/></label></div><div className="form-row"><label>Membership plan<select name="membership_plan_id" defaultValue=""><option value="">No plan yet</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></label><label>Starts on<input name="membership_starts_at" type="date"/></label></div>{errors.lead&&<em>{errors.lead}</em>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={processing}>{processing?'Converting…':'Convert to member'}</button></div></>}</Form></div>; }

function Payments({payments,create,edit}:{payments:PaymentRecord[];create:()=>void;edit:(payment:PaymentRecord)=>void}) { return <><section className="page-heading"><div><span className="eyebrow">FINANCE</span><h1>Payments</h1><p>Record membership payments and maintain a financial audit trail.</p></div><button className="primary" onClick={create}><Plus size={18}/> Record payment</button></section><div className="card members-card">{payments.length===0?<div className="compact-empty table-empty"><CreditCard/><strong>No payments recorded</strong><span>Record the first member payment to begin tracking revenue.</span><button className="secondary empty-state-action" onClick={create}>Record first payment</button></div>:<div className="payment-table"><div className="payment-row labels"><span>Member</span><span>Plan</span><span>Amount</span><span>Method</span><span>Status</span><span>Paid at</span><span>Actions</span></div>{payments.map(payment=><div className="payment-row" key={payment.id}><strong>{payment.memberName}</strong><span>{payment.plan??'Unassigned'}</span><strong>{new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(payment.amount))}</strong><span>{payment.paymentMethod}</span><i className={`status status-${payment.status}`}>{payment.status}</i><span>{payment.paidAt?new Date(payment.paidAt).toLocaleString('en-IN'):'Not paid'}</span><div className="row-actions"><button className="edit-action" onClick={()=>edit(payment)}><Pencil/></button>{payment.status==='pending'&&<button className="delete-action" onClick={()=>window.confirm('Delete this pending payment?')&&router.delete(`/admin/payments/${payment.id}`)}><Trash2/></button>}</div></div>)}</div>}</div></>; }

function PaymentModal({payment,members,methods,close}:{payment:PaymentRecord|null;members:PaymentMember[];methods:string[];close:()=>void}) { const now=new Date();const localDateTime=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);return <div className="modal-backdrop" onMouseDown={close}><Form action={payment?`/admin/payments/${payment.id}`:'/admin/payments'} method={payment?'put':'post'} className="modal" onMouseDown={event=>event.stopPropagation()} onSuccess={close}>{({errors,processing})=><><div className="modal-head"><div><h2>{payment?'Edit payment':'Record payment'}</h2><p>Attach a financial transaction to a gym member.</p></div><button type="button" onClick={close}><X/></button></div><label>Member<select name="user_id" defaultValue={payment?.memberId??''} required><option value="" disabled>Select a member</option>{members.map(member=><option key={member.id} value={member.id}>{member.name}{member.plan?` · ${member.plan}`:''}</option>)}</select>{errors.user_id&&<em>{errors.user_id}</em>}</label><div className="form-row"><label>Amount (₹)<input name="amount" type="number" min="0.01" step="0.01" defaultValue={payment?.amount??''} required/>{errors.amount&&<em>{errors.amount}</em>}</label><label>Status<select name="status" defaultValue={payment?.status??'paid'}><option value="paid">Paid</option><option value="pending">Pending</option><option value="refunded">Refunded</option><option value="failed">Failed</option></select>{errors.status&&<em>{errors.status}</em>}</label></div><div className="form-row"><label>Payment method<select name="payment_method" defaultValue={payment?.paymentMethod??methods[0]??'UPI'}>{(methods.length?methods:['UPI','Card','Cash','Bank transfer']).map(method=><option key={method}>{method}</option>)}</select>{errors.payment_method&&<em>{errors.payment_method}</em>}</label><label>Paid at<input name="paid_at" type="datetime-local" defaultValue={payment?.paidAt??localDateTime}/>{errors.paid_at&&<em>{errors.paid_at}</em>}</label></div><label>Reference<input name="reference" defaultValue={payment?.reference??''} placeholder="Optional transaction reference"/>{errors.reference&&<em>{errors.reference}</em>}</label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={processing}>{processing?'Saving…':'Save payment'}</button></div></>}</Form></div>; }

export default Dashboard;
